language: java
before_install:
  # setup android sdk
  - wget http://dl.google.com/android/android-sdk_r20-linux.tgz
  - tar -zxf android-sdk_r20-linux.tgz
  - export ANDROID_HOME=~/builds/jckimble/AdsLicenseChecker/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter 1,3,13,78,83 -a --no-ui --force
before_script:
  - cd ${ANDROID_HOME}/extras/google/play_licensing/library
  - android update project --path . --target android-8
  - ant release
  - cd ~/builds/jckimble/AdsLicenseChecker
  - android update project --path .
script: "ant dist"
notifications:
  email: false
